apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amq-broker.fullname" . }}
  labels:
    {{- include "amq-broker.labels" . | nindent 4 }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
    type: RollingUpdate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "amq-broker.brokerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "amq-broker.brokerSelectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "amq-broker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: AMQ_USER
            value: {{ include "amq-broker.userName" . }}
          - name: AMQ_PASSWORD
            value: {{ include "amq-broker.password" . }}
          - name: AMQ_TRANSPORTS
            value: {{ include "amq-broker.transports" . }}
          - name: AMQ_QUEUES
            value: {{ .Values.mq.queues }}
          - name: AMQ_TOPICS
            value: {{ .Values.mq.topics }}
          - name: MQ_SERIALIZABLE_PACKAGES
            value: {{ .Values.mq.serializablePackages }}
          {{- if .Values.storage.enabled }}
          - name: AMQ_SPLIT
            value: {{ include "amq-broker.split" . }}
          {{- end }}
          - name: AMQ_MESH_DISCOVERY_TYPE
            value: {{ .Values.mq.discoveryType }}
          - name: AMQ_MESH_SERVICE_NAME
            value: {{ include "amq-broker.fullname" . }}-mesh
          - name: AMQ_MESH_SERVICE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: AMQ_STORAGE_USAGE_LIMIT
            value: {{ .Values.mq.storageUsageLimit }}
          - name: AMQ_QUEUE_MEMORY_LIMIT
            value: {{ .Values.mq.queueMemoryLimit }}
          ports:
          - name: jolokia
            containerPort: 8778
            protocol: TCP
          - containerPort: 5672
            name: amqp
            protocol: TCP
          - containerPort: 1883
            name: mqtt
            protocol: TCP
          - containerPort: 61613
            name: stomp
            protocol: TCP
          - containerPort: 61616
            name: tcp
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/amq/bin/readinessProbe.sh
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or .Values.storage.enabled .Values.logging }}
          volumeMounts:
          {{- if .Values.storage.enabled }}
          - mountPath: /opt/amq/data
            name: {{ include "amq-broker.fullname" . }}-data
          {{- end }}
          {{- if .Values.logging }}
          - mountPath: /opt/amq/conf/log4j.properties
            name: {{ include "amq-broker.fullname" . }}-cm
            subPath: log4j.properties
          {{- end }}
      terminationGracePeriodSeconds: 60
      volumes:
      {{- if .Values.storage.enabled }}
      - name: {{ include "amq-broker.fullname" . }}-data
        persistentVolumeClaim:
          claimName: {{ include "amq-broker.fullname" . }}
      {{- end }}
      {{- if .Values.logging }}
      - name: {{ include "amq-broker.fullname" . }}-cm
        configMap:
          name: {{ include "amq-broker.fullname" . }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
