apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amq-broker.fullname" . }}-drainer
  labels:
    {{- include "amq-broker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "amq-broker.drainerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "amq-broker.drainerSelectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "amq-broker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-drainer
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /opt/amq/bin/drain.sh
          env:
          - name: AMQ_USER
            value: {{ include "amq-broker.userName" . }}
          - name: AMQ_PASSWORD
            value: {{ include "amq-broker.password" . }}
          - name: AMQ_MESH_DISCOVERY_TYPE
            value: {{ .Values.mq.discoveryType }}
          - name: AMQ_MESH_SERVICE_NAME
            value: {{ include "amq-broker.fullname" . }}-mesh
          - name: AMQ_MESH_SERVICE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
          - name: jolokia
            containerPort: 8778
            protocol: TCP
          - containerPort: 61616
            name: tcp
            protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.storage.enabled }}
          volumeMounts:
          - mountPath: /opt/amq/data
            name: {{ include "amq-broker.fullname" . }}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: {{ include "amq-broker.fullname" . }}
        persistentVolumeClaim:
          claimName: {{ include "amq-broker.fullname" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
