{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "amq-broker.fullname" . }}
  labels:
    {{- include "amq-broker.labels" . | nindent 4 }}
spec:
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}