{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: dpr-secret
metadata:
  name: {{ include "amq-consumer.serviceAccountName" . }}
  labels:
{{ include "amq-consumer.labels" . | nindent 4 }}
{{- end -}}
